enabled: False
python: |
  def while_try_except_else():
    arr = []
    while True:
      try:
        x = int(1)
        print(x)
      except ValueError:
        print("Oops!  That was not a valid number.  Try again...")
      else:
        res = True
        arr.append(1)
        break
    
    return res and arr == [1]